"""update tables

Revision ID: 2fbd0fe40ed1
Revises: 91fb43a4bea3
Create Date: 2025-08-24 04:44:41.101679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbd0fe40ed1'
down_revision = '91fb43a4bea3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('box', sa.Integer(), nullable=True))
    op.add_column('flashcards', sa.Column('next_review_date', sa.Date(), nullable=True))
    op.drop_column('flashcards', 'pronunciation')
    op.drop_column('flashcards', 'difficulty_level')
    op.drop_column('flashcards', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('flashcards', sa.Column('difficulty_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('flashcards', sa.Column('pronunciation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('flashcards', 'next_review_date')
    op.drop_column('flashcards', 'box')
    # ### end Alembic commands ###